name: 'dotnet-build.yml'

on:
  push:
    branches: ["main"]

jobs:
  Build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        dotnet-version: [8.0.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: 'Setup .NET'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Cache Dependencies
      uses: actions/cache@v3
      with:
        path: '**/obj/project.assets.json'
        key: dotnet-dependencies-${{ matrix.os }}-${{ hashFiles('**/project.assets.json') }}
        restore-keys: |
          dotnet-dependencies-${{ matrix.os }}-

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore
