on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  dotnet-dependency-review:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest]
        
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Setup .NET'
        uses: actions/setup-dotnet@v4

      - name: 'Restore Dependencies'
        run: dotnet restore

      - name: 'Run Dependency Review'
        uses: actions/dependency-review-action@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          retry-on-snapshot-warnings: false
          retry-on-snapshot-warnings-timeout: 120
          base_ref: ${{ github.event.before }}
          head_ref: ${{ github.sha }}
