name: 'dotnet-dependency.yml'

on:
  pull_request:
    branches: ["main"]

jobs:
  dependency-review:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest]
        dotnet-version: [6.0.x, 7.0.x, 8.0.x]
        
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Setup .NET'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: 'Restore Dependencies'
        run: dotnet restore

      - name: 'Run Dependency Review'
        uses: actions/dependency-review-action@v4
